# -*- coding: utf-8 -*-
"""nlp_lab5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hHK19HbO1c4EXNRVoftbSemqpAG1AGA_
"""

!pip install transformers

from sys import argv
import numpy as np
import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer
np.random.seed(42)
torch.manual_seed(42)

def generate(
            model, tok, text,
            do_sample=True, max_length=100, repetition_penalty=5.0,
            top_k=5, top_p=0.95, temperature=1,
            num_beams=None,
            no_repeat_ngram_size=3
            ):
          input_ids = tok.encode(text, return_tensors="pt")
          print(model.generate.__globals__['__file__'])
          out = model.generate(
              input_ids,
              max_length=max_length,
              repetition_penalty=repetition_penalty,
              do_sample=do_sample,
              top_k=top_k, top_p=top_p, temperature=temperature,
              num_beams=num_beams, no_repeat_ngram_size=no_repeat_ngram_size
              )
          return list(map(tok.decode, out))

model_name = 'sberbank-ai/rugpt3large_based_on_gpt2'
def load_tokenizer_and_model(model_name):
  return GPT2Tokenizer.from_pretrained(model_name), GPT2LMHeadModel.from_pretrained(model_name)

tok, model = load_tokenizer_and_model(model_name)

argv[1] = "В нашем торговом центре можно найти ювелирные украшения, одежду, обувь, кухонную утварь и ещё"
generated = generate(model, tok, argv[1], num_beams = 10)
print(generated[0])